package dev.vasas.flashbacker.persistence.dynamodb.entity

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = StoryEntity.storyTableName)
data class StoryEntity(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,

        @DynamoDBAttribute
        var userId: String? = null,

        @DynamoDBAttribute
        var location: String? = null,

        @DynamoDBAttribute
        var date: Long? = null,

        @DynamoDBAttribute
        var text: String? = null
) {

    companion object {
        const val storyTableName = "story"
    }
}
